runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/api/.*
  script: main.rpc_app

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
